artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_zar: artifacts/data_ingestion/

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  update_base_model_path: artifacts/prepare_base_model/base_model_updated.keras


prepare_callback:
  root_dir: artifacts/prepare_callback
  tensorboard_log_dir: artifacts/prepare_callback/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callback/checkpoint_dir/model.keras


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
